### ISSUE TITLE
Authy API changed? Onetouch-ssh no longer working.

### ISSUE THREAD

**Issue by SethAten** [dcu/onetouch-ssh#23]
So, extra work this morning, onetouch wasn't  working so I had to go in through the garage :)

`Sending approval request to your device... Post https://api.authy.com//onetouch/json/users/<redacted>/approval_requests: invalid request :path "//onetouch/json/users/<redacted>/approval_requests"ME@MINE:~$`

Guess Authy changed the API?

**Comment by dcu** [comment]
should be fixed now, can you try again?

**Comment by SethAten** [comment]
Yep, works now. Coupled with Authy now allowing requests to be answered in-notification, better than ever!

**Comment by dcu** [comment]
so just to clarify, the issue was that CloudFlare (which runs in front of the api.authy.com) started enforcing HTTP/2  by mistake when releasing Warp ( https://blog.cloudflare.com/introducing-cloudflare-warp/ ). `go-authy` was adding an extra slash in front of the path so the requests looked like `api.authy.com//foo/bar` and Go 1.8 ( https://github.com/golang/go/issues/19103 ) has a bug when the path has that double slash and HTTP/2 is used. 
So it was a combination of 3 issues.
